In [100]:
# Basic Modules
import pandas as pd
import numpy as np
import scipy as stats
from scipy.stats import skew

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

In [101]:
# Load cleaned data files into pandas DataFrames
# 'ISO-8859-1' encoding is used for building_descriptions_df to handle special characters
# that would cause issues with the default 'utf-8' encoding

yearly_vals_df = pd.read_csv("C:/Users/barre/Alexandria Personal Project/Cleaned Data/cleaned_yearly_values.csv")
sales_df = pd.read_csv("C:/Users/barre/Alexandria Personal Project/Cleaned Data/cleaned_sales_data.csv")
build_descrips_df = pd.read_csv("C:/Users/barre/Alexandria Personal Project/Cleaned Data/cleaned_building_descriptions.csv", encoding='ISO-8859-1')

In [102]:
yearly_vals_df.head()

,account_num,land_value,building_value,total_value,zip_code,levy_month,levy_year
0,50467480,103179,233965,337144,22302,1,2024
1,50467480,96328,195787,292115,22302,1,2023
2,50467480,91741,186464,278205,22302,1,2022
3,50467480,91741,186464,278205,22302,1,2021
4,50467480,79775,162142,241917,22302,1,2020

In [103]:
yearly_vals_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1622004 entries, 0 to 1622003
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   account_num     1622004 non-null  int64
 1   land_value      1622004 non-null  int64
 2   building_value  1622004 non-null  int64
 3   total_value     1622004 non-null  int64
 4   zip_code        1622004 non-null  int64
 5   levy_month      1622004 non-null  int64
 6   levy_year       1622004 non-null  int64
dtypes: int64(7)
memory usage: 86.6 MB

In [104]:
sales_df.head()

        num  sale_price  sale_month  sale_day  sale_years
0  15890000     1200000           7        23        2009
1  15890000      289000           7        30        1999
2  15890000      259000          10        25        1994
3  15890000      114900           3        22        1985
4  11497500     2050000          10        17        2018

In [105]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344490 entries, 0 to 344489
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   num         344490 non-null  int64
 1   sale_price  344490 non-null  int64
 2   sale_month  344490 non-null  int64
 3   sale_day    344490 non-null  int64
 4   sale_years  344490 non-null  int64
dtypes: int64(5)
memory usage: 13.1 MB

In [106]:
build_descrips_df.head()

,account_num,year_built,construction_quality,building_condition,hvac,building_type,gross_building_area,net_leasable_area
0,50466800,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
1,50466810,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
2,50466820,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
3,50466830,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN
4,50466840,1961,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,NaN,NaN

In [107]:
build_descrips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17728 entries, 0 to 17727
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   account_num           17728 non-null  int64
 1   year_built            17728 non-null  int64
 2   construction_quality  17728 non-null  object
 3   building_condition    17728 non-null  object
 4   hvac                  17728 non-null  object
 5   building_type         17728 non-null  object
 6   gross_building_area   2451 non-null   object
 7   net_leasable_area     2451 non-null   object
dtypes: int64(2), object(6)
memory usage: 1.1+ MB

In [108]:
# Check for duplicates in the DataFrames and remove them
yearly_vals_df = yearly_vals_df.rename(columns={'levy_year':'year'})
print("Levy duplicates:", yearly_vals_df.duplicated(subset=['account_num', 'year']).sum())
yearly_vals_df = yearly_vals_df.drop_duplicates(subset=['account_num', 'year'])
print("Levy duplicates:", yearly_vals_df.duplicated(subset=['account_num', 'year']).sum())

sales_df = sales_df.rename(columns={'num':'account_num', 'sale_years':'year'})
print("Sales duplicates:", sales_df.duplicated(subset=['account_num', 'year', 'sale_month']).sum())
sales_df = sales_df.drop_duplicates(subset=['account_num', 'year', 'sale_month'])
print("Sales duplicates:", sales_df.duplicated(subset=['account_num', 'year', 'sale_month']).sum())

print("Building duplicates:", build_descrips_df.duplicated(subset=['account_num', 'year_built']).sum())
build_descrips_df = build_descrips_df.drop_duplicates(subset=['account_num', 'year_built'])
print("Sales duplicates:", build_descrips_df.duplicated(subset=['account_num', 'year_built']).sum())

Levy duplicates: 837570
Levy duplicates: 0
Sales duplicates: 230293
Sales duplicates: 0
Building duplicates: 0
Sales duplicates: 0

In [109]:
# Check for missing values in the DataFrames
print("Missing values in yearly_vals_df (by column):")
print(yearly_vals_df.isna().sum())

print("Missing values in sales_df (by column):")
print(sales_df.isna().sum())

print("Missing values in build_descrips_df (by column):")
print(build_descrips_df.isna().sum())

Missing values in yearly_vals_df (by column):
account_num       0
land_value        0
building_value    0
total_value       0
zip_code          0
levy_month        0
year              0
dtype: int64
Missing values in sales_df (by column):
account_num    0
sale_price     0
sale_month     0
sale_day       0
year           0
dtype: int64
Missing values in build_descrips_df (by column):
account_num                 0
year_built                  0
construction_quality        0
building_condition          0
hvac                        0
building_type               0
gross_building_area     15277
net_leasable_area       15277
dtype: int64

In [110]:
# Drop rows with mostly missing values in building_descrips_df
build_descrips_df.drop(columns=['gross_building_area', 'net_leasable_area'], inplace = True)
# Check for missing values again after dropping columns
build_descrips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17728 entries, 0 to 17727
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   account_num           17728 non-null  int64
 1   year_built            17728 non-null  int64
 2   construction_quality  17728 non-null  object
 3   building_condition    17728 non-null  object
 4   hvac                  17728 non-null  object
 5   building_type         17728 non-null  object
dtypes: int64(2), object(4)
memory usage: 831.1+ KB

In [111]:
# Step 1: Get the most recent building description for each property
building_descriptions = build_descrips_df.sort_values('year_built').groupby('account_num').last().reset_index()

# Step 2: Create all possible property-year combinations
all_years = pd.concat([
    yearly_vals_df[['account_num', 'year']],
    sales_df[['account_num', 'year']]
]).drop_duplicates()

# Step 3: Merge building descriptions FIRST (before year filtering)
master_df = all_years.merge(building_descriptions, on='account_num', how='left')

# Step 4: Only nullify building info for years BEFORE construction
has_building_info = ~master_df['year_built'].isna()
mask = (master_df['year'] < master_df['year_built']) & has_building_info
building_cols = ['year_built', 'construction_quality', 'building_condition', 'hvac', 'building_type']
master_df.loc[mask, building_cols] = np.nan

In [112]:
# Step 5: Now merge with assessment and sales data
master_df = master_df.merge(
    yearly_vals_df,
    on=['account_num', 'year'],
    how='left'
)

master_df = master_df.merge(
    sales_df,
    on=['account_num', 'year'],
    how='left'
)

# Final cleanup
master_df = master_df.sort_values(['account_num', 'year'])

In [114]:
master_df[master_df['account_num'] == 50466800].head()

,account_num,year,year_built,construction_quality,building_condition,hvac,building_type,land_value,building_value,total_value,zip_code,levy_month,sale_price,sale_month,sale_day
783290,50466800,2001,1961.0,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,109529.0,248721.0,358250.0,22302.0,1.0,51000.0,11.0,1.0
785755,50466800,2002,1961.0,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,17700.0,48500.0,66200.0,22302.0,1.0,NaN,NaN,NaN
785754,50466800,2003,1961.0,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,29300.0,52800.0,82100.0,22302.0,1.0,NaN,NaN,NaN
785753,50466800,2004,1961.0,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,38100.0,78000.0,116100.0,22302.0,1.0,NaN,NaN,NaN
785752,50466800,2005,1961.0,GOOD,GOOD,CENTRAL AIR TO AIR,CONDO > 3 STORIES,47600.0,137700.0,185300.0,22302.0,1.0,NaN,NaN,NaN

In [115]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843413 entries, 323576 to 263887
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   account_num           843413 non-null  int64
 1   year                  843413 non-null  int64
 2   year_built            346728 non-null  float64
 3   construction_quality  346728 non-null  object
 4   building_condition    346728 non-null  object
 5   hvac                  346728 non-null  object
 6   building_type         346728 non-null  object
 7   land_value            786529 non-null  float64
 8   building_value        786529 non-null  float64
 9   total_value           786529 non-null  float64
 10  zip_code              786529 non-null  float64
 11  levy_month            786529 non-null  float64
 12  sale_price            114197 non-null  float64
 13  sale_month            114197 non-null  float64
 14  sale_day              114197 non-null  float64
dtypes: float64(9), int64(2), object(4)
memory usage: 103.0+ MB

In [142]:
cat_df = master_df[['year','account_num', 'construction_quality', 'building_condition', 'hvac', 'building_type']]

num_df = master_df.select_dtypes(include='number')

In [143]:
cat_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843413 entries, 323576 to 263887
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   year                  843413 non-null  int64
 1   account_num           843413 non-null  int64
 2   construction_quality  346728 non-null  object
 3   building_condition    346728 non-null  object
 4   hvac                  346728 non-null  object
 5   building_type         346728 non-null  object
dtypes: int64(2), object(4)
memory usage: 45.0+ MB

In [118]:
num_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843413 entries, 323576 to 263887
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   account_num     843413 non-null  int64
 1   year            843413 non-null  int64
 2   year_built      346728 non-null  float64
 3   land_value      786529 non-null  float64
 4   building_value  786529 non-null  float64
 5   total_value     786529 non-null  float64
 6   zip_code        786529 non-null  float64
 7   levy_month      786529 non-null  float64
 8   sale_price      114197 non-null  float64
 9   sale_month      114197 non-null  float64
 10  sale_day        114197 non-null  float64
dtypes: float64(9), int64(2)
memory usage: 77.2 MB

In [120]:
# 1. Calculate building_age (will be NaN if year_built is missing)
num_df['building_age'] = num_df['year'] - num_df['year_built']

# 2. Flag sales (1 if sale occurred, 0 otherwise)
num_df['had_sale'] = num_df['sale_price'].notna().astype(int)

# 3. Fill sale-related columns with 0 where no sale occurred
sale_cols = ['sale_price', 'sale_month', 'sale_day']
num_df[sale_cols] = num_df[sale_cols].fillna(0)

# 3.5 Define function to compute last sale year and price before each year for each property
def compute_last_sales(group):
    # Sort the data for this property chronologically
    group = group.sort_values('year')

    last_years = []
    last_prices = []

    # Loop through each row in the group
    for _, row in group.iterrows():
        # Filter past sales with sale_price > 0 before current year
        past_sales = group[(group['sale_price'] > 0) & (group['year'] < row['year'])]

        if not past_sales.empty:
            last_sale = past_sales.iloc[-1]  # most recent past sale
            last_years.append(last_sale['year'])
            last_prices.append(last_sale['sale_price'])
        else:
            last_years.append(float('nan'))
            last_prices.append(float('nan'))

    # Add results as new columns
    group['last_sale_year'] = last_years
    group['last_sale_price'] = last_prices

    return group

# Apply the function by property
num_df = num_df.groupby('account_num', group_keys=False).apply(compute_last_sales)

# 4. Forward-fill value columns to carry assessments forward
num_df = num_df.sort_values(['account_num', 'year'])
value_cols = ['land_value', 'building_value', 'total_value', 'zip_code', 'levy_month']
num_df[value_cols] = num_df.groupby('account_num')[value_cols].ffill()

# 5. Remove rows with both land_value and building_value missing or zero, unless a sale occurred
condition = (
    num_df[['land_value', 'building_value']].fillna(0).eq(0).all(axis=1) & 
    (num_df['had_sale'] == 0)
)
num_df = num_df[~condition]

# 6. Forward-fill 'last_sale_year' within each property (if needed)
num_df['last_sale_year'] = num_df.groupby('account_num')['last_sale_year'].ffill()

# 7. Calculate years since last sale (NaN if no sale ever occurred)
num_df['years_since_last_sale'] = num_df['year'] - num_df['last_sale_year']

C:\Users\barre\AppData\Local\Temp\ipykernel_184492\2428061042.py:39: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  num_df = num_df.groupby('account_num', group_keys=False).apply(compute_last_sales)

In [137]:
num_df_filled = num_df[~num_df['total_value'].isna()].copy()
num_df_filled = num_df_filled.drop(columns=['year_built', 'had_sale', 'levy_month'])

In [138]:
num_df_filled.head()

,account_num,year,land_value,building_value,total_value,zip_code,sale_price,sale_month,sale_day,building_age,last_sale_year,last_sale_price,years_since_last_sale
323576,10006030,2001,0.0,0.0,0.0,22314.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
323575,10006030,2002,0.0,0.0,0.0,22314.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
323574,10006030,2003,0.0,0.0,0.0,22314.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
323573,10006030,2004,0.0,0.0,0.0,22314.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
323572,10006030,2005,0.0,0.0,0.0,22314.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [124]:
for col in cat_df.columns[2:]:
    print(f"Unique values in {col}:")
    print(cat_df[col].unique())
    print()

Unique values in construction_quality:
[nan 'GOOD' 'GOOD PLUS' 'AVERAGE PLUS' 'VERY GOOD' 'AVERAGE'
 'VERY GOOD PLUS' 'EXCELLENT' 'FAIR PLUS' 'LOW PLUS' 'FAIR' '.' 'LOW' '`']

Unique values in building_condition:
[nan 'GOOD' 'POOR' 'AVERAGE' 'FAIR' 'VERY GOOD' 'EXCELLENT']

Unique values in hvac:
[nan 'COMPLETE HVAC' 'WARM AND COOL AIR ZONE' 'PACKAGE UNIT'
 'HOT CHILLED WATER' 'HEAT PUMP INDIVIDUAL UNIT'
 'HOT WATER BASE BOARD W/AC' 'HOT WATER' 'RADIATOR W/AC'
 'HOT WATER BASEBOARD' 'HEAT PUMP' 'SPACE HEATER' 'NONE'
 'CENTRAL AIR TO AIR' 'FORCED AIR' 'ELECTRIC WALL' 'ELECTRIC'
 'ELECTRIC BASEBOARD' 'WALL UNIT/ELECTRIC W/AC' 'ERROR'
 'COOL AIR IN HEAT DUCTS']

Unique values in building_type:
[nan 'MAIL PROCESSING FACILITY' 'OFFICE BUILDING' 'RESTAURANT'
 'DISCOUNT STORE' 'MIXED RETAIL W/ OFFICE UNITS'
 'MIXED RETAIL W/ RES UNITS' 'VETERINARY HOSPITAL'
 'INDUST HEAVY MANUFACTURING' 'EXTENDED STAY MOTELS' 'RETAIL STORE'
 '3 STORY' 'MULTIPLE - RESIDENTIAL' 'INDUSTRIAL FLEX MALL BUILDING'
 '2½ STORY' '2 STORY' 'CONDO <= 3 STORIES' 'DENTAL OFFICE/ CLINIC'
 'SERVICE GARAGE' 'COMMUNITY RECREATION CENTER' 'DAY CARE CENTER'
 'SERVICE STATION' 'BARBER/BEAUTY SHOP' 'FAST FOOD RESTAURANT' 'CHURCH'
 'AUTOMOTIVE CENTER' 'APARTMENTS (HI-RISE)' 'APARTMENT > 3 STORIES'
 'MINI WAREHOUSE HI-RISE' 'CAR WASH - AUTOMATIC'
 'LUXURY APARTMENTS HI-RISE' 'MORTUARY' 'MEDICAL OFFICES' 'DRUG STORE'
 '2.25 STORY FIN' 'HOTEL' 'LUXURY BOUTIQUES' 'FELLOWSHIP HALLS'
 'SCHOOL - CLASSROOM' 'LODGES' 'THEATRE - MOTION' 'PERMIT VALUE' 'LIBRARY'
 'CONVENIENCE STORE' 'GROUP CARE HOMES' 'BANK' 'GUEST COTTAGES'
 'SCHOOL - ELEMENTARY/SECONDARY' 'THEATRE - STAGE' '1½ STORY FIN'
 'CONDO > 3 STORIES' 'SUPERMARKET' '3.25 STORY FIN' 'FRATERNAL BUILDING'
 '3.5 STORY FIN' 'STORAGE WAREHOUSE' 'MINI WAREHOUSE' 'SELF SERVICE BOOTH'
 '1 STORY' 'NEIGHBORHOOD SHOPPING CENTER' 'CONVLSNT HOSP NURSING HOME'
 'TOWNHOUSE TWO STORY' 'COMPLETE AUTO DEALERSHIP' 'MODULAR OFFICE'
 'LAUNDRY/DRY CLEANING' 'DISTRIBUTION WAREHOUSE'
 'WAREHOUSE SHOWROOM STORE' 'KENNEL' 'INDUST LGHT MANUFACTURING'
 'GOVERNMENT BUILDING' 'MINI LUBE GARAGE' 'STORAGE GARAGE' 'STABLE'
 'COMMUNITY SHOPPING CENTER' 'SENIOR (CLUBHOUSE) CENTERS'
 'TRANSIT WAREHOUSE' 'SURGICAL CENTER - OUT PATIENT'
 'HOME FOR THE ELDERLY' '2.75 STORY FIN' 'DORMITORY RESIDENCE HALLS'
 'COLLEGE - ENTIRE' 'SCHOOL - GYMNASIUM' 'HANDBALL/RAQUETBALL COURTS/CLUB'
 'SCHOOL - SCIENCE BUILDING' 'SCHOOL - FINE ARTS BUILDING'
 'APARTMENT <= 3 STORIES' 'HOTELS - LIMITED SERVICE' '4 STORY FIN'
 'COLLEGE - CLASSROOMS' 'MUSEUM' 'EQUIPMENT BUILDING'
 'COMMUTER TERMINAL, AIRLINE, BUS' 'PARKING LEVELS' 'TOWNHOUSE 3  STORY'
 'HOSPITAL' 'CONDO PKS' 'FIRING RANGE BUILDINGS' 'TOWNHOUSE 2 1/2 STORY'
 'TOWNHOUSE 3 1/2 STORY' 'CLUBHOUSE' 'MULTIPLE - ELDERLY ASSISTED LIVING'
 'ROOMING HOUSES' 'REGIONAL SHOPPING CENTER'
 'LIGHT INDUSTRIAL SHELL BUILDINGS']

In [144]:
cat_df.loc[:, 'construction_quality'] = cat_df['construction_quality'].replace({'.': np.nan, '`': np.nan})
cat_df.loc[:, 'construction_quality'] = cat_df['construction_quality'].fillna('MISSING')

cat_df.loc[:, 'building_condition'] = cat_df['building_condition'].fillna('MISSING')

# To reduce the cardanlity of 'hvac', domain-informed feature engineering can be applied
'''
Unique values in hvac:
[nan 'COMPLETE HVAC' 'WARM AND COOL AIR ZONE' 'PACKAGE UNIT'
 'HOT CHILLED WATER' 'HEAT PUMP INDIVIDUAL UNIT'
 'HOT WATER BASE BOARD W/AC' 'HOT WATER' 'RADIATOR W/AC'
 'HOT WATER BASEBOARD' 'HEAT PUMP' 'SPACE HEATER' 'NONE'
 'CENTRAL AIR TO AIR' 'FORCED AIR' 'ELECTRIC WALL' 'ELECTRIC'
 'ELECTRIC BASEBOARD' 'WALL UNIT/ELECTRIC W/AC' 'ERROR'
 'COOL AIR IN HEAT DUCTS']
'''
hvac_map = {
    'HOT CHILLED WATER': 'HOT WATER',
    'HOT WATER BASE BOARD W/AC': 'HOT WATER',
    'HOT WATER BASEBOARD': 'HOT WATER',
    'HEAT PUMP INDIVIDUAL UNIT': 'HEAT PUMP', 
    'ELECTRIC BASEBOARD': 'ELECTRIC',
    'ELECTRIC WALL': 'ELECTRIC',
    'WALL UNIT/ELECTRIC W/AC': 'ELECTRIC',
    np.nan: 'UKNOWN', 
    'ERROR': 'UKNOWN',
}

cat_df.loc[:, 'hvac_grouped'] = cat_df['hvac'].replace(hvac_map)

C:\Users\barre\AppData\Local\Temp\ipykernel_184492\800575649.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df.loc[:, 'hvac_grouped'] = cat_df['hvac'].replace(hvac_map)

In [145]:
'''
Unique values in building_type:
[nan 'MAIL PROCESSING FACILITY' 'OFFICE BUILDING' 'RESTAURANT'
 'DISCOUNT STORE' 'MIXED RETAIL W/ OFFICE UNITS'
 'MIXED RETAIL W/ RES UNITS' 'VETERINARY HOSPITAL'
 'INDUST HEAVY MANUFACTURING' 'EXTENDED STAY MOTELS' 'RETAIL STORE'
 '3 STORY' 'MULTIPLE - RESIDENTIAL' 'INDUSTRIAL FLEX MALL BUILDING'
 '2½ STORY' '2 STORY' 'CONDO <= 3 STORIES' 'DENTAL OFFICE/ CLINIC'
 'SERVICE GARAGE' 'COMMUNITY RECREATION CENTER' 'DAY CARE CENTER'
 'SERVICE STATION' 'BARBER/BEAUTY SHOP' 'FAST FOOD RESTAURANT' 'CHURCH'
 'AUTOMOTIVE CENTER' 'APARTMENTS (HI-RISE)' 'APARTMENT > 3 STORIES'
 'MINI WAREHOUSE HI-RISE' 'CAR WASH - AUTOMATIC'
 'LUXURY APARTMENTS HI-RISE' 'MORTUARY' 'MEDICAL OFFICES' 'DRUG STORE'
 '2.25 STORY FIN' 'HOTEL' 'LUXURY BOUTIQUES' 'FELLOWSHIP HALLS'
 'SCHOOL - CLASSROOM' 'LODGES' 'THEATRE - MOTION' 'PERMIT VALUE' 'LIBRARY'
 'CONVENIENCE STORE' 'GROUP CARE HOMES' 'BANK' 'GUEST COTTAGES'
 'SCHOOL - ELEMENTARY/SECONDARY' 'THEATRE - STAGE' '1½ STORY FIN'
 'CONDO > 3 STORIES' 'SUPERMARKET' '3.25 STORY FIN' 'FRATERNAL BUILDING'
 '3.5 STORY FIN' 'STORAGE WAREHOUSE' 'MINI WAREHOUSE' 'SELF SERVICE BOOTH'
 '1 STORY' 'NEIGHBORHOOD SHOPPING CENTER' 'CONVLSNT HOSP NURSING HOME'
 'TOWNHOUSE TWO STORY' 'COMPLETE AUTO DEALERSHIP' 'MODULAR OFFICE'
 'LAUNDRY/DRY CLEANING' 'DISTRIBUTION WAREHOUSE'
 'WAREHOUSE SHOWROOM STORE' 'KENNEL' 'INDUST LGHT MANUFACTURING'
 'GOVERNMENT BUILDING' 'MINI LUBE GARAGE' 'STORAGE GARAGE' 'STABLE'
 'COMMUNITY SHOPPING CENTER' 'SENIOR (CLUBHOUSE) CENTERS'
 'TRANSIT WAREHOUSE' 'SURGICAL CENTER - OUT PATIENT'
 'HOME FOR THE ELDERLY' '2.75 STORY FIN' 'DORMITORY RESIDENCE HALLS'
 'COLLEGE - ENTIRE' 'SCHOOL - GYMNASIUM' 'HANDBALL/RAQUETBALL COURTS/CLUB'
 'SCHOOL - SCIENCE BUILDING' 'SCHOOL - FINE ARTS BUILDING'
 'APARTMENT <= 3 STORIES' 'HOTELS - LIMITED SERVICE' '4 STORY FIN'
 'COLLEGE - CLASSROOMS' 'MUSEUM' 'EQUIPMENT BUILDING'
 'COMMUTER TERMINAL, AIRLINE, BUS' 'PARKING LEVELS' 'TOWNHOUSE 3  STORY'
 'HOSPITAL' 'CONDO PKS' 'FIRING RANGE BUILDINGS' 'TOWNHOUSE 2 1/2 STORY'
 'TOWNHOUSE 3 1/2 STORY' 'CLUBHOUSE' 'MULTIPLE - ELDERLY ASSISTED LIVING'
 'ROOMING HOUSES' 'REGIONAL SHOPPING CENTER'
 'LIGHT INDUSTRIAL SHELL BUILDINGS']
 '''
# Grouping building types into broader categories to reduce cardinality
def simplify_building_type(x):
    if pd.isna(x): return 'MISSING'
    x = x.upper()
    if 'APARTMENT' in x or 'CONDO' in x or 'TOWNHOUSE' in x or 'RESIDENTIAL' in x or 'DORMITORY' in x:
        return 'RESIDENTIAL'
    elif 'RETAIL' in x or 'STORE' in x or 'RESTAURANT' in x or 'SHOPPING' in x or 'SUPERMARKET' in x or 'BOUTIQUE' in x:
        return 'RETAIL'
    elif 'OFFICE' in x or 'BANK' in x or 'GOVERNMENT' in x:
        return 'OFFICE'
    elif 'WAREHOUSE' in x or 'INDUST' in x or 'STORAGE' in x:
        return 'INDUSTRIAL'
    elif 'HOTEL' in x or 'MOTEL' in x or 'GUEST COTTAGE' in x:
        return 'HOSPTITALITY'
    elif 'SCHOOL' in x or 'COLLEGE' in x or 'CLASSROOM' in x:
        return 'EDUCATION'
    elif 'HOSP' in x or 'SURGICAL' in x or 'MEDICAL' in x or 'CLINIC' in x:
        return 'HEALTHCARE'
    elif 'CHURCH' in x or 'HALL' in x or 'CLUB' in x or 'LIBRARY' in x or 'MUSEUM' in x:
        return 'CIVIC'
    elif 'AUTO' in x or 'GARAGE' in x or 'STATION' in x or 'CAR WASH' in x:
        return 'AUTO'
    else:
        return 'OTHER'

cat_df.loc[:, 'building_type_grouped'] = cat_df['building_type'].apply(simplify_building_type)

C:\Users\barre\AppData\Local\Temp\ipykernel_184492\1232072249.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df.loc[:, 'building_type_grouped'] = cat_df['building_type'].apply(simplify_building_type)

In [146]:
cat_df.head()

,year,account_num,construction_quality,building_condition,hvac,building_type,hvac_grouped,building_type_grouped
323576,2001,10006030,MISSING,MISSING,NaN,NaN,UKNOWN,MISSING
323575,2002,10006030,MISSING,MISSING,NaN,NaN,UKNOWN,MISSING
323574,2003,10006030,MISSING,MISSING,NaN,NaN,UKNOWN,MISSING
323573,2004,10006030,MISSING,MISSING,NaN,NaN,UKNOWN,MISSING
323572,2005,10006030,MISSING,MISSING,NaN,NaN,UKNOWN,MISSING

In [147]:
cat_df = cat_df.drop(columns=['hvac', 'building_type'])
cat_df.rename(columns={'hvac_grouped': 'hvac', 'building_type_grouped': 'building_type'})
cat_df.head()

,year,account_num,construction_quality,building_condition,hvac_grouped,building_type_grouped
323576,2001,10006030,MISSING,MISSING,UKNOWN,MISSING
323575,2002,10006030,MISSING,MISSING,UKNOWN,MISSING
323574,2003,10006030,MISSING,MISSING,UKNOWN,MISSING
323573,2004,10006030,MISSING,MISSING,UKNOWN,MISSING
323572,2005,10006030,MISSING,MISSING,UKNOWN,MISSING

In [139]:
num_df_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 786941 entries, 323576 to 263887
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   account_num            786941 non-null  int64
 1   year                   786941 non-null  int64
 2   land_value             786941 non-null  float64
 3   building_value         786941 non-null  float64
 4   total_value            786941 non-null  float64
 5   zip_code               786941 non-null  float64
 6   sale_price             786941 non-null  float64
 7   sale_month             786941 non-null  float64
 8   sale_day               786941 non-null  float64
 9   building_age           321408 non-null  float64
 10  last_sale_year         720321 non-null  float64
 11  last_sale_price        720321 non-null  float64
 12  years_since_last_sale  720321 non-null  float64
dtypes: float64(11), int64(2)
memory usage: 84.1 MB

In [148]:
cat_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 843413 entries, 323576 to 263887
Data columns (total 6 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   year                   843413 non-null  int64
 1   account_num            843413 non-null  int64
 2   construction_quality   843413 non-null  object
 3   building_condition     843413 non-null  object
 4   hvac_grouped           843413 non-null  object
 5   building_type_grouped  843413 non-null  object
dtypes: int64(2), object(4)
memory usage: 45.0+ MB

In [172]:
tableua_export_df = pd.merge(num_df_filled, cat_df, on=['year', 'account_num'], how='inner')
tableua_export_df["zip_code"] = tableua_export_df["zip_code"].astype(int)

In [175]:
tableua_export_df.head()

,account_num,year,land_value,building_value,total_value,zip_code,sale_price,sale_month,sale_day,building_age,last_sale_year,last_sale_price,years_since_last_sale,construction_quality,building_condition,hvac_grouped,building_type_grouped
0,10006030,2001,0.0,0.0,0.0,22314,0.0,0.0,0.0,NaN,NaN,NaN,NaN,MISSING,MISSING,UKNOWN,MISSING
1,10006030,2002,0.0,0.0,0.0,22314,0.0,0.0,0.0,NaN,NaN,NaN,NaN,MISSING,MISSING,UKNOWN,MISSING
2,10006030,2003,0.0,0.0,0.0,22314,0.0,0.0,0.0,NaN,NaN,NaN,NaN,MISSING,MISSING,UKNOWN,MISSING
3,10006030,2004,0.0,0.0,0.0,22314,0.0,0.0,0.0,NaN,NaN,NaN,NaN,MISSING,MISSING,UKNOWN,MISSING
4,10006030,2005,0.0,0.0,0.0,22314,0.0,0.0,0.0,NaN,NaN,NaN,NaN,MISSING,MISSING,UKNOWN,MISSING

In [176]:
tableua_export_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791233 entries, 0 to 791232
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   account_num            791233 non-null  int64
 1   year                   791233 non-null  int64
 2   land_value             791233 non-null  float64
 3   building_value         791233 non-null  float64
 4   total_value            791233 non-null  float64
 5   zip_code               791233 non-null  int64
 6   sale_price             791233 non-null  float64
 7   sale_month             791233 non-null  float64
 8   sale_day               791233 non-null  float64
 9   building_age           323574 non-null  float64
 10  last_sale_year         723465 non-null  float64
 11  last_sale_price        723465 non-null  float64
 12  years_since_last_sale  723465 non-null  float64
 13  construction_quality   791233 non-null  object
 14  building_condition     791233 non-null  object
 15  hvac_grouped           791233 non-null  object
 16  building_type_grouped  791233 non-null  object
dtypes: float64(10), int64(3), object(4)
memory usage: 102.6+ MB

In [177]:
tableua_export_df.to_csv("C:\\Users\\barre\\Alexandria Personal Project\\Tableua\\tableua_export.csv", index=False)